specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
features: 
  - grafting
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: {{network}}
    source:
      address: "{{factory.address}}"
      abi: Factory
      startBlock: {{factory.startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/factory.ts
      entities:
        - Protocol
      abis:
        - name: Factory
          file: ./abis/uniswap-v2/Factory.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      callHandlers:
        - function: setFeeTo(address)
          handler: handleFeeTo
