name: Actions
on: 
  pull_request: 
    branches:
      - master
    types: [closed]
jobs:
  Deploy:
    name: Pull Request
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: echo "Github Action - Deploying subgraphs to Messari"
      - run: npm install -g @graphprotocol/graph-cli
      - run: npm install --dev @graphprotocol/graph-ts
      - run: npm install mustache
      - run: yarn install
      - run: graph auth --product hosted-service 0845de8b9d834db8b16b5c97ba33ec53
      - run: cd subgraphs/uniswap-forks
      - run: npm run deploy uniswap-v2 steegecs
        working-directory: subgraphs/uniswap-forks



 