name: Actions
on: 
  pull_request: 
    branches:
      - master
    types: [closed]
jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        uses: [actions/checkout@v3, actions/setup-node@v3]
      - run: echo "Github Action - Deploying subgraphs to Messari Hosted Service"


 