name: Actions
on: 
  pull_request: 
    branches:
      - master
    types: [closed]
jobs:
  Deployment:
    name: Pull Reques
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true

    - id: get-id
      run: |
        declare -i deploy_all
        declare -A deploy_protocol
        declare -A deploy_network
        deploy_all=0
        ip=$( echo "$line" |cut -d\: -f1 )

        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ ${changed_file} == *"/src/"* ]]; then
            ref_folder=$( echo ${changed_file%/src/*} | rev | cut -d / -f 2| rev);
            if [[ $ref_folder == subgraphs ]]; then
              deploy_all=1;
            elif [[ $ref_folder == protocols ]]; then
              deploy_protocol[protocol]=1;
            else 
              echo "Warning: src/ folder should be located at subgraphs/**subgraph**/protocols/src/ or subgraphs/**subgraph**/src/"; 
            fi;
          elif [[ ${changed_file} == *"/config/"* ]]; then
            ref_folder=$( echo ${changed_file%/config/*} | rev | cut -d / -f 2| rev);
            if [[ $ref_folder == protocols ]]; then
              ref_folder2=( echo ${changed_file} | rev | cut -d / -f 2| rev);
              if [[ $ref_folder2 != config ]]
                deploy_network[$ref_folder, $ref_folder2] = 1;
              fi;
            else 
              echo "Warning: config/ folder should be located at subgraphs/**subgraph**/protocols/config/";
            fi;
          fi;
        done
    - run: echo "${{steps.get-id.outputs.id}}"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: echo "${{ github.head_ref }} Github Action - Deploying subgraphs to Messari"
    - run: npm install -g @graphprotocol/graph-cli
    - run: npm install --dev @graphprotocol/graph-ts
    - run: npm install mustache
    - run: yarn install
    - run: graph auth --product hosted-service 0845de8b9d834db8b16b5c97ba33ec53
    - run: cd subgraphs/uniswap-forks
    - run: npm run deploy uniswap-v2 steegecs
      working-directory: subgraphs/uniswap-forks



 