name: Actions
on: 
  pull_request: 
    branches:
      - master
    types: [closed]
jobs:
  Deployment:
    name: Pull Reques
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true

    - id: get-id
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ changed_file == *"/src/"* ]]; then
            echo changed_file;
            export srcPath=${changed_file%/src/*})
            id=$(echo srcPath | rev | cut -d / -f 1| rev)
            echo "::set-output name=id::$id"; fi;
        done
    - run: echo "${{steps.get-id.outputs.id}}"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: echo "${{ github.head_ref }} Github Action - Deploying subgraphs to Messari"
    - run: npm install -g @graphprotocol/graph-cli
    - run: npm install --dev @graphprotocol/graph-ts
    - run: npm install mustache
    - run: yarn install
    - run: graph auth --product hosted-service 0845de8b9d834db8b16b5c97ba33ec53
    - run: cd subgraphs/uniswap-forks
    - run: npm run deploy uniswap-v2 steegecs
      working-directory: subgraphs/uniswap-forks



 